WARNING  Not Found: /test_package/simple_404/
ERROR  Internal Server Error: /test_package/simple_404/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 150, in get_response
    response = callback(request, **param_dict)
  File "D:\Python27\lib\site-packages\django\utils\decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\views\defaults.py", line 20, in page_not_found
    t = loader.get_template(template_name) # You need to create a 404.html template.
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: 404.html
ERROR  Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "H:\AptanaWorkspace\environment2\src\mTurk1\views.py", line 79, in tasks_no_match
    return render_to_response('mTurk1/not_validated.html',{'key_status':key_status,'url_key':url_key},context_instance=RequestContext(request))
  File "D:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 20, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    t = get_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: mTurk1/not_validated.html
ERROR  Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "H:\AptanaWorkspace\environment2\src\mTurk1\views.py", line 79, in tasks_no_match
    return render_to_response('mTurk1/not_validated.html',{'key_status':key_status,'url_key':url_key},context_instance=RequestContext(request))
  File "D:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 20, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    t = get_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: mTurk1/not_validated.html
ERROR  Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "H:\AptanaWorkspace\environment2\src\mTurk1\views.py", line 79, in tasks_no_match
    return render_to_response('mTurk1/not_validated.html',{'key_status':key_status,'url_key':url_key},context_instance=RequestContext(request))
  File "D:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 20, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    t = get_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: mTurk1/not_validated.html
ERROR  Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "H:\AptanaWorkspace\environment2\src\mTurk1\views.py", line 79, in tasks_no_match
    return render_to_response('mTurk1/not_validated.html',{'key_status':key_status,'url_key':url_key},context_instance=RequestContext(request))
  File "D:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 20, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    t = get_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: mTurk1/not_validated.html
ERROR  Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "H:\AptanaWorkspace\environment2\src\mTurk1\views.py", line 79, in tasks_no_match
    return render_to_response('mTurk1/not_validated.html',{'key_status':key_status,'url_key':url_key},context_instance=RequestContext(request))
  File "D:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 20, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    t = get_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: mTurk1/not_validated.html
ERROR  Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "H:\AptanaWorkspace\environment2\src\mTurk1\views.py", line 79, in tasks_no_match
    return render_to_response('mTurk1/not_validated.html',{'key_status':key_status,'url_key':url_key},context_instance=RequestContext(request))
  File "D:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 20, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    t = get_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: mTurk1/not_validated.html
ERROR  Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "H:\AptanaWorkspace\environment2\src\mTurk1\views.py", line 79, in tasks_no_match
    return render_to_response('mTurk1/not_validated.html',{'key_status':key_status,'url_key':url_key},context_instance=RequestContext(request))
  File "D:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 20, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    t = get_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: mTurk1/not_validated.html
WARNING  Not Found: /test_package/simple_404/
ERROR  Internal Server Error: /test_package/simple_404/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 150, in get_response
    response = callback(request, **param_dict)
  File "D:\Python27\lib\site-packages\django\utils\decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\views\defaults.py", line 20, in page_not_found
    t = loader.get_template(template_name) # You need to create a 404.html template.
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: 404.html
ERROR  Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "H:\AptanaWorkspace\environment2\src\mTurk1\views.py", line 79, in tasks_no_match
    return render_to_response('mTurk1/not_validated.html',{'key_status':key_status,'url_key':url_key},context_instance=RequestContext(request))
  File "D:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 20, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    t = get_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: mTurk1/not_validated.html
ERROR  Internal Server Error: /test_package/shnkj
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "H:\AptanaWorkspace\environment2\src\mTurk1\views.py", line 79, in tasks_no_match
    return render_to_response('mTurk1/not_validated.html',{'key_status':key_status,'url_key':url_key},context_instance=RequestContext(request))
  File "D:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 20, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    t = get_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: mTurk1/not_validated.html
ERROR  Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "H:\AptanaWorkspace\environment2\src\mTurk1\views.py", line 79, in tasks_no_match
    return render_to_response('mTurk1/not_validated.html',{'key_status':key_status,'url_key':url_key},context_instance=RequestContext(request))
  File "D:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 20, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    t = get_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: mTurk1/not_validated.html
ERROR  Internal Server Error: /test_package/shnkj
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "H:\AptanaWorkspace\environment2\src\mTurk1\views.py", line 79, in tasks_no_match
    return render_to_response('mTurk1/not_validated.html',{'key_status':key_status,'url_key':url_key},context_instance=RequestContext(request))
  File "D:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 20, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    t = get_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: mTurk1/not_validated.html
ERROR  Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "H:\AptanaWorkspace\environment2\src\mTurk1\views.py", line 79, in tasks_no_match
    return render_to_response('mTurk1/not_validated.html',{'key_status':key_status,'url_key':url_key},context_instance=RequestContext(request))
  File "D:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 20, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    t = get_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: mTurk1/not_validated.html
ERROR  Internal Server Error: /test_package/shnkj
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "H:\AptanaWorkspace\environment2\src\mTurk1\views.py", line 79, in tasks_no_match
    return render_to_response('mTurk1/not_validated.html',{'key_status':key_status,'url_key':url_key},context_instance=RequestContext(request))
  File "D:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 20, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    t = get_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: mTurk1/not_validated.html
ERROR  Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "H:\AptanaWorkspace\environment2\src\mTurk1\views.py", line 79, in tasks_no_match
    return render_to_response('mTurk1/not_validated.html',{'key_status':key_status,'url_key':url_key},context_instance=RequestContext(request))
  File "D:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 20, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    t = get_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: mTurk1/not_validated.html
ERROR  Internal Server Error: /test_package/simple_date_time
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "H:\AptanaWorkspace\environment2\src\mTurk1\views.py", line 79, in tasks_no_match
    return render_to_response('mTurk1/not_validated.html',{'key_status':key_status,'url_key':url_key},context_instance=RequestContext(request))
  File "D:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 20, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    t = get_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: mTurk1/not_validated.html
ERROR  Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "H:\AptanaWorkspace\environment2\src\mTurk1\views.py", line 79, in tasks_no_match
    return render_to_response('mTurk1/not_validated.html',{'key_status':key_status,'url_key':url_key},context_instance=RequestContext(request))
  File "D:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 20, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    t = get_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: mTurk1/not_validated.html
